import Head from 'next/head'
import DefaultLayout from '@/layout/defaultLayout'
import Hero from "@/components/hero"
import CardSection from '@/components/cardsection'
import FilteredList from '@/components/filteredlist'
import Info from '@/components/info'
import RandomSection from '@/components/randomsection'
import styles from '@/styles/Home.module.scss'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="src\assets\images\logo.svg" />
      </Head>
      <DefaultLayout>
        <main className={styles.Main}>
          <Hero />
          <FilteredList data={data}/>
          {/* <CardSection data={data} /> */}
          <Info data={data} />
          {/* <RandomSection data={data} /> */}
        </main>
      </DefaultLayout>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`https://api.npoint.io/421e815a115c2fcb3b68`);
  const data = res.status === 200 ? await res.json() : {};

  return { props: { data } };
}



//  Call by ID or index https://api.npoint.io/421e815a115c2fcb3b68/0/id